spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: xxxx
    password: xxxx
  thymeleaf:
    cache: false
    prefix: classpath:templates
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template-location: false

mybatis:
  type-aliases-package: com.andy.shiro.entity.rbac
  mapper-locations: classpath:mybatis/mappers/*.xml

module:
  shiro:
    multiLogin: false
    cacheDays: 7
    redisPrefix: ${server.port}
    anonUrls:
    - /api/user/property
    - /api/user/login
    csrfUrls: /**
    authUrls: /**
    tokenPrefix: auth.token.


